MetaMask/smart-transactions-controller

.github/workflows/publish-release.yml, scripts/check-release.sh
This PR adds config so that we can automatically deploy packages to npm on release.
Opening as a Draft for now until the `environment` (`npm-publish`) is configured.
I've tested this in my fork here: https://github.com/rickycodes/smart-transactions-controller/actions/runs/2667509178
TODO:
=> Add config for `MetaMask/action-npm-publish`

src/SmartTransactionsController.ts
This PR removes unnecessary props, which are no longer needed for making our product better. We added them initially because we thought they could be useful for debugging. We have also just noticed that token_from_address and token_to_address fields don't even use correct values. All these 3 event props are not needed, so we are removing them and we will also clean them up in our database. This issue affected a small subset of users who opted in MetaMetrics and submitted transactions through our embedded Swaps feature with Smart Transactions enabled. 
If you think we have somewhere in MM an unnecessary event prop, let us please know via GitHub issue.
=> Remove unnecessary event props

package.json, src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/utils.ts, yarn.lock
This is https://github.com/MetaMask/metamask-extension/pull/15461 to remove any ethers submodules that are not used in the extension dependency tree by replacing all imports of ethers for the used submodule itself
CHANGED:
- Simply replaces the "umbrella" version of ethers with the submodules that we actually use: @ethersproject/bytes , @ethersproject/providers & @ethersproject/bignumber.
=> Replace `ethers` with submodules

src/SmartTransactionsController.ts
A `try...finally` block has been added to ensure that the nonce is always released, even when an error is thrown.
=> Ensure the nonce lock is always released

README.md, package.json
The module template README contains placeholder content that is designed to be replaced when a new library is created from the template. This updates the README to suit this library.
=> Replace placeholders in README

CHANGELOG.md, package.json, src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/index.test.ts, src/types.ts, yarn.lock
Wallets shouldn't be directly concerned about the network ID as this more of a p2p concept for gossip. What wallets really care about is chain ID as that is the correct value to use to identify a chain, build transactions, etc. Although these two values usually match (ignoring hex/dec formatting), there are [exceptions](https://medium.com/@pedrouid/chainid-vs-networkid-how-do-they-differ-on-ethereum-eec2ed41635b).
We want to remove usage of `networkId` from the SmartTransactionController.
* Fixes [mmp-1068](https://github.com/MetaMask/MetaMask-planning/issues/1068)
* See: [core-1633](https://github.com/MetaMask/core/pull/1633)
* See: https://github.com/MetaMask/metamask-extension/pull/20652
=> Remove networkId

jest.config.js, package.json, src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/constants.ts, src/index.test.ts, src/types.ts, yarn.lock
Resolves: https://github.com/MetaMask/MetaMask-planning/issues/1039
Integrates new `PollingController` abstraction into the `SmartTransactionsController`, implements the `_executePoll` method and parameterizes the `updateSmartTransactions` method by networkClientId such that pending SmartTransaction statuses can be polled for concurrently across different chains.
A note: As is our current controller refactor strategy, these changes are additive, backwards compatible and coexist alongside the existing globally selected network pattern. Once we fully adopt this polling pattern we should no longer access the root `liveness` and `fees` state but rather access these values by chainId from `livenessByChainId` and `feesByChainId`.
- Integrates `PollingController` mixin into the …
=> Parameterize SmartTransactionsController state by ChainId for MultiChain + Integrate PollingController Mixin

src/SmartTransactionsController.test.ts
Just removes some comment code accidentally left in https://github.com/MetaMask/smart-transactions-controller/pull/210
=> remove commented code

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts
We are adding a new "userOptInV2" prop, since we are updating our backend and need users to re-approve Smart Swaps.
=> Add a new "userOptInV2" prop

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/utils.test.ts, src/utils.ts, tsconfig.json
Add the "stxControllerVersion" query param for the `/submitTransactions` API call. That's because then backend can have custom logic based on the version.
=> Stx controller version

jest.config.js, package.json, src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/constants.ts, src/index.test.ts, src/types.ts, yarn.lock
This reverts commit a9f500404ebc7efdcf2d0e97ca740150ed8e727a.
This reverts the PR https://github.com/MetaMask/smart-transactions-controller/pull/210, because it introduces a bug that we need to identify. We are electing to revert it for now because we wish to push out new swaps feature and quickly get them into the latest RC.
We will re-introduce these changes in a subsequent PR with full E2E testing insuring that the bug is fixed.
=> Revert "Parameterize SmartTransactionsController state by ChainId for MultiChain + Integrate PollingController Mixin

package.json, src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/types.ts, yarn.lock
This PR does 2 things:
- Adds support for more transactions
- Emits events, so it's easier to understand what's going on with a transaction status
- Make a build with this PR, include it in the MM extension and make sure Smart Swaps still work
=> Add support for more transactions, emit events

package.json, src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/types.ts, src/utils.test.ts, src/utils.ts, yarn.lock
This PR includes multiple things:
- Emit an event after a tx is confirmed
- Remove "skipConfirm"
- Return "txHash"
- Change to: `public eventEmitter: EventEmitter;`
=> Emit an event after a tx is confirmed, remove "skipConfirm", return "txHash"

package.json, src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/index.test.ts, src/types.ts, src/utils.test.ts, yarn.lock
When used outside of Swaps, the TransactionController usually confirms completed smart transactions, unless a user closes a browser before a smart transaction is completed. We only want to call the `confirmExternalTransaction` function if a transaction wasn't already confirmed.
=> Confirm only a tx that wasn't already confirmed

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/constants.ts, src/types.ts
This PR does a few things:
- Updates a domain name from `https://transaction.metaswap.codefi.network` to `https://transaction.api.cx.metamask.io`
- Adds new props on the `SmartTransactionsStatus` type
- Adds a new function `getSmartTransactionByMinedTxHash`
=> Update domain name for transaction-api, add a new function "getSmartTransactionByMinedTxHash"

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts
Fix a condition in the "wipeSmartTransations" function, update tests.
=> Fix a condition in the "wipeSmartTransations" function

src/SmartTransactionsController.ts
We have to emit an event with an updated Smart Transaction first before confirmation, because then a txHash is returned to the TransactionController once it's available and the `#doesTransactionNeedConfirmation` function will work properly, since it will find the txHash in the regular transactions list.
- Opt into Smart Transactions
- Submit a Send transaction on Sepolia
- Once it's finished, you can check that the `Transaction Finalized` event is only triggered once
=> Emit an event with a Smart Transaction before confirmation

src/SmartTransactionsController.ts
When a user switched a network and came back, the `poll` function was called multiple times. Now it's only called once.
1. Submit a Send transaction on Sepolia testnet
2. Switch to Ethereum mainnet when your transaction from 1. is pending
3. After a minute switch back to Sepolia
4. The `/batchStatus` network call is only done once and the `STX Confirmed` event is only trigged once
=> fix: Call the "poll" function only once on a network switch

package.json, yarn.lock
Ensuring latest version is of `@metamask/transaction-controller` can be used with this package.
---
- #345 
---
- https://github.com/MetaMask/core/blob/main/packages/transaction-controller/CHANGELOG.md
=> deps: @metamask/transaction-controller@^29.1.0->^30.0.0

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts
We [fixed this issue](https://github.com/MetaMask/smart-transactions-controller/pull/347), eliminating an edge case related to network switching where we were unnecessarily polling for transaction status.
This PR improves state management to ensure unique smart transactions, and includes code to fix this issue for a small subset of users who have encountered this issue. The code to fix the issue for this subset of users will be removed in a future version once we have confirmed this is resolved.
=> fix: Improve state management

yarn.lock
Resolves this Dependabot alert: https://github.com/advisories/GHSA-78xj-cgh5-2h22
=> Update yarn.lock for the `socks` module

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/utils.ts
This PR updates metrics for 2 events and includes a bit of refactoring, which was needed to make the events work for non-swaps transactions.
=> Update metrics, refactoring

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/index.test.ts, src/types.ts, src/utils.ts
Save new event props to a newly created smart transaction, so they can be used in anonymised metrics (only if a user opted into them).
=> Save new event props to a newly created smart transaction, use both `properties` and `sensitiveProperties` for events

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts
Fix metrics and improve tests.
=> fix: Metrics

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts
This PR reverts code from [#353](https://github.com/MetaMask/smart-transactions-controller/pull/353), which is no longer needed, since the issue that was happening for a small subset of users was already solved in production.
=> chore: Remove code that is no longer needed

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/constants.ts, src/utils.test.ts, src/utils.ts
We want to stop using transaction-api and use Sentinel instead. This is the first step in that journey: migrating the health API checkpoint.
=> chore: Use a new API for a health check

src/SmartTransactionsController.ts, src/index.ts
Emit a new "smartTransactionConfirmationDone" event, which can be used in the extension and mobile.
=> Emit a new "smartTransactionConfirmationDone" event

src/constants.ts
Adds ReceiveRequest to MetaMetricsEventName and Navigation to MetaMetricsEventCategory for this issue:
https://github.com/MetaMask/MetaMask-planning/issues/3260
=> Add MetaMetricsEvents

.eslintrc.js, package.json, tsconfig.build.json, tsconfig.json, tsconfig.test.json
This project has two kinds of TypeScript config files, which is consistent with the module template. However, whereas in the module template, the default config file (`tsconfig.json`) is the one used for development and `tsconfig.build.json` is used to build the project, in this repo it's reversed (`tsconfig.test.json` used for development).
This commit aligns the kinds of TypeScript configuration files with the module template. It also normalizes the existing options to fit the module template. There should be no differences to `dist/`.
=> Standardize tsconfig files

package.json, src/SmartTransactionsController.test.ts, src/utils.test.ts, src/utils.ts, yarn.lock
The `@lavamoat/preinstall-always-fail` package has been added, and the package `eslint-plugin-import` package has been downgraded by a minor version, both to meet `peerDependency` requirements of other development dependencies.
The import plugin downgrade resulted in new lint warnings about import order, which were addressed.
Resolves two warnings, no functional changes.
=> chore: Fix development `peerDependency` warnings

tsconfig.build.json
`tsconfig.build.json` is now instructing TypeScript to only emit type declaration files instead of also emitting JavaScript files. This change was erroneously made in a previous commit. This commit removes that instruction.
- Run `yarn build`
- Inspect `dist/`. You should see `.js` and `.js.map` files in addition to `.d.ts` files.
=> Fix tsconfig to emit JS files in addition to declarations

package.json, yarn.lock
The `@metamask/network-controller` and `@metamask/transaction-controller` dependencies have been moved from `dependencies` to `peerDependencies` (and `devDependencies`). This was done because we're not directly importing and using those controllers directly from imports, they're instead passed in as constructor parameters (indirectly), so it's critical that the versions we use here match the versions used on the client exactly.
The peer dependency requirements of those two packages have been silenced because they aren't actually instantiated here, just used for type purposes (so we don't need their `peerDependencies` present).
=> chore: Recategorize controllers as peer dependencies

package.json, yarn.lock
This dependency was not used anywhere. Previously it was brought in because an older version of this controller extended `EventEmitter`, but even then the package wasn't really used (the Node.js events module was resolved instead).
We're not even using `EventEmitter` anymore since the migration to the `BaseControllerV2` base class.
=> chore: Remove unnecessary `events` dependency

CHANGELOG.md, package.json, src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/index.test.ts, src/types.ts, yarn.lock
Update `@metamask/transaction-controller` peer dependency from `38.0.0` to `42.0.0`
Breaking changes introduced in version `41.0.0` of `@metamask/transaction-controller` affect `@metamask/smart-transactions-controller`. These changes involve the removal of global network usage, requiring the explicit configuration of `networkClientId`. [CHANGELOG](https://github.com/MetaMask/core/blob/main/packages/transaction-controller/CHANGELOG.md?plain=1#L71)
=> chore: Update `@metamask/transaction-controller` peer dependency to `42.0.0`

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/types.ts, src/utils.test.ts, src/utils.ts
Extends definition of when a regular tx is marked as failed (only if we return a txHash asap) and clean up unsupported statuses.
=> fix: Extend definition of when a regular tx is marked as failed, clean up unsupported statuses

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts
feat: Enable Persistence for SmartTransactionsController
Adds state persistence for the SmartTransactionsController, enables access to historical STX data across browser sessions.
Changes:
- Set `persist: true` in `SmartTransactionsController` metadata
- Added `updateState` public method for testing purposes
- Implemented test to verify state persistence between controller instances
- Updated initialization test to confirm persistence is enabled
Benefits
Allows migration scripts and other features to access and utilize historical smart transaction data after browser restarts, improving data continuity and application functionality.
* Fixes #12345
* See: [EXT - #28854](https://github.com/MetaMask/metamask-extension/pull/28854/files#diff-fd9867707661a47627f22edcf23756d1b2bbb0cff370f62e1218d9 …
=> Fix: SmartTransactionsController `state` should persist

src/constants.ts, src/utils.test.ts
**Description**
This change enables the STX controller to communicate with the Base network's Sentinel API
**What is the current state of things and why does it need to change?**
Currently, the STX controller supports Ethereum Mainnet, BSC, and Ethereum Sepolia networks via the `SENTINEL_API_BASE_URL_MAP` in `constants.ts`. However, there is no support for the Base network, which needs to be added as part of the "STX with auctions on Base" epic.
**What is the solution your changes offer and how does it work?**
This PR adds Base network support to the Smart Transactions Controller by:
Adding the Base chain ID (8453) to the `SENTINEL_API_BASE_URL_MAP` in `constants.ts`
Adding a test case in `utils.test.ts` to verify the Base Sentinel endpoint works correctly
These changes enable the STX …
=> feat: add Base Sentinel endpoint to STX controller

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/types.ts
This PR adds support for submitting batch transactions.
=> feat: Support batch transactions during submit

src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts
This PR improves error handling and monitoring and resolves a rare edge case where an error could be thrown after successful STX submission, which prevented status polling from happening.
=> fix: Improve error handling and monitoring

CHANGELOG.md, jest.config.js, package.json, scripts/prepack.sh, tsconfig.build.json, tsconfig.json, yarn.lock
Switch to `ts-bridge` so that we can publish this package in both ES module format and CommonJS module format, and add `exports` to `package.json` to instruct bundlers which format they should choose. (Note that this is a breaking change as consumers will no longer be allowed to import subpaths.) The exports are double-checked with `@arethetypeswrong/cli` to ensure that they work correctly.
- Run `yarn`.
- Run `yarn build`.
- Review `dist/` to ensure that it contains all files that are needed to co1nsume this package.
- Run `yarn test`.
- There should be a report from `attw` at the end. It should pass.
=> Switch to ts-bridge and harden exports

CHANGELOG.md, src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts
The new metadata properties `includeInStateLogs` and `usedInUi` have been added to `SmartTransactionController`.
* Fixes https://github.com/MetaMask/core/issues/6509
* Related to https://github.com/MetaMask/core/issues/6443
=> feat: Add new metadata properties

CHANGELOG.md, package.json, yarn.lock
There have been some changes to the `TransactionMeta` package but there should be no functional changes to this package.
Changelog here: https://github.com/MetaMask/core/blob/71b6bb6530f363d36475ca3d8f6029595fe508bd/packages/transaction-controller/CHANGELOG.md
=> Upgrade `transaction-controller` peer dep to v60

CHANGELOG.md, package.json, src/SmartTransactionsController.test.ts, src/SmartTransactionsController.ts, src/index.test.ts, src/types.ts, src/utils.test.ts, src/utils.ts, yarn.lock
Currently, the constructor takes `getNonceLock`, `confirmExternalTransaction`, `getTransactions`, and `updateTransaction` options. In practice these are references to methods within TransactionController. This commit removes these options and calls the TransactionController methods via the messenger instead. 
As this requires that consumers include more actions in the SmartTransactionControllerMessenger allowlist, this is a breaking change.
=>  Remove fn references to TransactionController in favor of messenger 
